spring:
  application:
    name: nevera
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    # Supabase 대시보드의 URI 정보를 분해해서 입력합니다.
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXP}
  refresh-expiration: ${JWT_REFRESH_EXP}

google:
  client-id: ${GOOGLE_CLIENT_ID}
